services:
  radarr:
    image: binhex/arch-radarr
    container_name: binhex-radarr-v2
    environment:
      - PUID=99
      - PGID=100
      - UMASK=000
      - TZ=Asia/Jerusalem
    ports:
      - "7878:7878"
    volumes:
      - /mnt/user/appdata/binhex-radarr:/config
      - /mnt/user/Movies:/media
      - /mnt/user/downloads:/data
      - /mnt/user/downloads/incomplete:/data/incomplete
      # - binhex-shared:/shared
    restart: unless-stopped
    networks:
      - arr-network
    privileged: true
    security_opt:
      - label=disable

  sonarr:
    image: binhex/arch-sonarr
    container_name: binhex-sonarr-v2
    environment:
      - PUID=99
      - PGID=100
      - UMASK=000
      - TZ=Asia/Jerusalem
    ports:
      - "8989:8989"
      - "9897:9897"
    volumes:
      - /mnt/user/appdata/binhex-sonarr:/config
      - /mnt/user/TV_Shows:/media
      - /mnt/user/appdata/data:/data
      - /mnt/user/downloads/incomplete:/data/incomplete
    restart: unless-stopped
    networks:
      - arr-network
    privileged: true
    security_opt:
      - label=disable

  prowlarr:
    image: ghcr.io/binhex/arch-prowlarr
    container_name: binhex-prowlarr-v2
    environment:
      - PUID=99
      - PGID=100
      - UMASK=000
      - TZ=Asia/Jerusalem
    ports:
      - "9696:9696"
    volumes:
      - /mnt/user/appdata/binhex-prowlarr:/config
    restart: unless-stopped
    networks:
      - arr-network

  telegram-bot-radarr:
    image: woiza/telegram-bot-radarr
    container_name: telegram-bot-radarr-v2
    environment:
      - TZ=Asia/Jerusalem
      - RBOT_BOT_ALLOWED_USERIDS=5003945996
      - RBOT_RADARR_HOSTNAME=radarr
      - RBOT_RADARR_API_KEY=#
      - RBOT_RADARR_PORT=7878
      - RBOT_RADARR_PROTOCOL=http
      - RBOT_BOT_IGNORE_TAGS=true
      - RBOT_BOT_MAX_ITEMS=10
      - RBOT_TELEGRAM_BOT_TOKEN=#
      - RADARR_CUSTOM_FOLDER=/media/movies
    user: "appuser"
    restart: unless-stopped
    networks:
      - arr-network

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr-v2
    environment:
      - PUID=99
      - PGID=100
      - TZ=Asia/Jerusalem
      - LOG_LEVEL=info
      - UMASK=022
    ports:
      - "5055:5055"
    volumes:
      - /mnt/user/appdata/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - arr-network
    privileged: true
    security_opt:
      - label=disable

  deluge:
    image: binhex/arch-deluge
    container_name: binhex-deluge-v2
    environment:
      - PUID=99
      - PGID=100
      - UMASK=000
      - TZ=Asia/Jerusalem
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
    ports:
      - "8112:8112"
      - "58846:58846"
      - "58946:58946"
      - "58946:58946/udp"
    volumes:
      - /mnt/user/appdata/binhex-deluge:/config
      - /mnt/cache/downloads:/data
      # - /mnt/user/Movies:/data/movies
      # - /mnt/user/audiobooks:/data/audiobook
      # - binhex-shared:/shared
    restart: unless-stopped
    networks:
      - arr-network
    privileged: true
    security_opt:
      - label=disable
    cpuset: "0,1,2"

  flaresolverr:
    image: binhex/arch-flaresolverr
    container_name: binhex-flaresolverr-v2
    environment:
      - PUID=99
      - PGID=100
      - UMASK=000
      - TZ=Asia/Jerusalem
    ports:
      - "8191:8191"
    volumes:
      - /mnt/user/appdata/binhex-flaresolverr:/config
    restart: unless-stopped
    networks:
      - arr-network
    privileged: true
    security_opt:
      - label=disable
      
networks:
  arr-network:
    name: arr-network
